main:
  #components_repository: "https://github.com/udacity/build-ml-pipeline-for-short-term-rental-prices#components"
  # All the intermediate files will be copied to this directory at the end of the run.
  # Set this to null if you are running in prod
  project_name: ObjectDetectionSystem
  experiment_name: DATAGATHER
  steps: MODELING_MAIN

DATAGATHER:
  video_sampling: True
  discard_ratio: 0.7
  autolabel: True
  model_name: fasterrcnn_resnet50
  detection_threshold: 0.9
  resize: 1920,1080,3
  input_video_folder: D:\videos
  root_output_folder: ./sample_output
  artifact_name: video_gathering
  artifact_type: folder
  artifact_description: video_sampling_to_detection

EDA:
  DATASET_ANALYSIS:
    images_dir: C:\Users\fonso\Documents\sample_output\subset\images
    labels_dir: C:\Users\fonso\Documents\sample_output\subset\labels
    plots_output_dir: ./generated_images
    report_save_dir: ./report_output
    artifact_name: EDA_REPORT.pdf
    artifact_type: report
    artifact_description: A_brief_summary_of_the_dataset

  VISUALIZER:
    dataset_format: VOC
    root_input_dir: C:\Users\fonso\Documents\sample_output\subset
    root_output_dir:
    artifact_name: Visualizer
    artifact_type: visualizer
    artifact_description: Visualization_of_labels


PREPROCESSING:
  class_list: goalkeeper,player,ball,referee

  ANNOTATION_CONVERSOR:
    perform: False
    src_label_format: VOC
    dst_label_format: COCO
    input_label_dir: C:\Users\fonso\Documents\Data\FootballerDetection\raw_data\labels
    output_label_dir: ./coco_labels
    artifact_name: coco_labels
    artifact_type: annotations_folder
    artifact_description: COCO_Annotations_for_footballer_detection

  AUGMENTATIONS:
    perform: True
    image_directory: C:\Users\fonso\Documents\Data\FootballerDetection\raw_data\images
    labels_directory: C:\Users\fonso\Documents\Data\FootballerDetection\raw_data\labels
    augmentations_file: RandomRain.yml
    merge_augmented_images: True
    artifact_name: augmentations
    artifact_type: augmentations_result
    artifact_description: Augmentation_file_used_And_result

  EXTRA_PREPROCESSING:
    type: erase_images_with_empty_labels
    image_directory: C:\Users\fonso\Documents\sample_output\subset\images
    labels_directory: C:\Users\fonso\Documents\sample_output\subset\labels
    labels_to_maintain: ball
    current_labels_list: ball
    target_labels_list: ball
    artifact_name: extra_preprocessing
    artifact_type: folder
    artifact_description: removed_extra_labels

MODELING:
  dataset_format: VOC
  class_list: ball
  images_dir: C:\Users\fonso\Documents\tiles\images
  labels_dir: C:\Users\fonso\Documents\tiles\labels
  output_dir: ./model_output_tiled
  train_split: 0.8
  model: fasterrcnn_resnet50
  train_config:
    batch_size: 1
    optimizer:
      name: SGD
      params:
        lr: 1e-5
    scheduler:
      name: CosineAnnealingWarmRestarts
      params:
        T_0: 50
    epochs: 20
  artifact_name: modeling
  artifact_type: torch_model
  artifact_description: Model_Produced

  MODEL_SELECTION:
    model_list: fasterrcnn_resnet50,fcos_resnet_50fpn
    metric_criteria: MAP
    K: 5
    selection_method: K_Crossval
    hypothesis_test: PAIRWISE_TTEST
    significance_level: 0.05
    artifact_name: model_selection
    artifact_type: torch_model
    artifact_description: Model_Produced

  INFERENCE:
    inference_type: dataset
    input_folder: C:\Users\fonso\Documents\sample_output\images
    output_folder: C:\Users\fonso\Documents\model_tiled_inference
    model_name: fasterrcnn_resnet50
    checkpoint: C:\Users\fonso\Documents\ObjectDetectionPackage\model_output_tiled\BEST_FasterRCNN.pth
    detection_threshold: 0.95
    resize: 1280,720
    artifact_name: inference_data
    artifact_type: inference
    artifact_description: dataset_to_infere

#C:\Users\fonso\Documents\sample_output\images



